Remove TEXTRELs from Linux/x86 qtWebkit
There are refs to absolute symbols in the Webkit JIT
which cause failure to load on SELinux:

ImportError: ../miniconda/envs/test-spy/lib/python2.7/site-packages/PyQt5/../../../libQt5WebKit.so.5: cannot restore segment prot after reloc: Permission denied